# ─── Global defaults ────────────────────────────────────────────────────────────
model: o3                    # strong reasoning; still quick enough for CLI use
provider: openai             # leave as-is unless you add Azure/OpenRouter keys

# ==== Autonomy ====
# • suggest     = never writes files or runs shell without asking
# • auto-edit   = writes files automatically, but still asks before any shell cmd
# • full-auto   = no questions asked (sandboxed shell)
approvalMode: auto-edit      # safest “hands-off” that still saves you clicking “yes” 20×/day

# ==== UI tweaks ====
notify: true                 # Windows toast when a long run finishes
history:
  maxSize: 200               # keeps CLI snappy; older context trimmed

# ==== Reliability ====
maxRetries: 3                # smooths over transient 502/RateLimit errors
timeoutSeconds: 120          # fail fast if the model hangs

# ==== Cost control ====
# Use a cheaper model for one-liners (override with  -m  on the CLI)
quickModel: o4-mini          # fast + cheap for “explain this line” or Q&A
